org: scientist1995
app: demo
service: aws-dynamo-global-tables-project
frameworkVersion: '3'

provider:
  name: aws

resources:
  Resources:
    myTable:
      Type: AWS::DynamoDB::GlobalTable
      Properties:
        TableName: myTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Replicas:
          - Region: us-east-1
          - Region: us-west-1
